apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-demo-app
  name: nginx-demo-app
  namespace: spinnaker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-demo-app
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
      labels:
        app: nginx-demo-app
    spec:
      containers:
        - image: 'dnzmfr/nginx-demo:0.4'
          name: nginx-demo-app
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-service
  namespace: spinnaker
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx-demo-app
  type: LoadBalancer
