{
 "title": "Canary Demo App Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Requests (200, 500) - Total ",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "requests_total{app=\"canary-demo-app\", app_kubernetes_io_managed_by=\"spinnaker\", app_kubernetes_io_name=\"canary-demo-app\"}",
     "legendFormat": "http_code {{http_code}} : {{instance}}"
    }
   ]
  },
  {
   "title": "HTTP 200 Requests - Total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "requests_total{app=\"canary-demo-app\", app_kubernetes_io_managed_by=\"spinnaker\", app_kubernetes_io_name=\"canary-demo-app\", http_code=\"200\"}",
     "legendFormat": "http_code 200 : {{instance}}"
    }
   ]
  },
  {
   "title": "HTTP 500 Requests - Total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "requests_total{app=\"canary-demo-app\", app_kubernetes_io_managed_by=\"spinnaker\", app_kubernetes_io_name=\"canary-demo-app\", http_code=\"500\"}",
     "legendFormat": "http_code 500 : {{instance}}"
    }
   ]
  }
 ]
}