apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: canary-demo-app
  name: canary-demo
  namespace: spinnaker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: canary-demo-app
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
      labels:
        app: canary-demo-app
    spec:
      containers:
        - image: 'dnzmfr/canary-demo:0.1'
          name: canary-demo-pod
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 2
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: canary-demo
  namespace: spinnaker
  labels:
    app: canary-demo-app
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: canary-demo-app
  type: LoadBalancer

