apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: canary-demo-app
  name: canary-demo-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: canary-demo-app
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8000'
      labels:
        app: canary-demo-app
    spec:
      containers:
        - image: 'dnzmfr/canary-demo:latest'
          name: canary-demo-app-pod
          ports:
            - containerPort: 80
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: canary-demo-service
  namespace: default
  labels:
    app: canary-demo-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: canary-demo-app
  type: LoadBalancer

